services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: django_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./messenger_backend/
    restart: unless-stopped
    command: sh -c "ls -la && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./messenger_backend:/app
    expose:
      - "8000"
    environment:
      DEBUG: "True"
      DB_NAME: django_db
      DB_USER: django_user
      DB_PASSWORD: django_pass
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build:
      context: ./messenger_app/
      target: production # Use the production stage
    restart: unless-stopped
    ports:
      - "80:80" # Main port for the app
    depends_on:
      - backend

volumes:
  postgres_data:
