services:
  backend:
    build: ./messenger_backend/
    restart: unless-stopped
    command: sh -c "ls -la && python manage.py migrate --noinput && daphne -b 0.0.0.0 -p 8000 messenger_backend.asgi:application"
    volumes:
      - ./messenger_backend:/app
      - django_static:/app/static
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      context: ./messenger_app/
      target: production # Use the production stage
    restart: unless-stopped
    volumes:
      - django_static:/usr/share/nginx/html/static
    ports:
      - "80:80" # Main port for the app
      - "443:443"
    depends_on:
      - backend

volumes:
  django_static:
